---
title: "Histerical Squares"
author: "John Walker"
date: 2020-06-26T21:13:14-05:00
categories: ["R"]
tags: ["Generative"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Histerical Squares

 Tweaking code provided by @quantixed <https://quantixed.org/2019/05/26/turn-a-square-generative-art/> This function will make grid art arguments define the number of squares in each dimension (xSize, ySize) grout defines the gap between squares (none = 0, max = 1) hFactor defines the amount of hysteresis (none = 0, max = 1, moderate = 10)

```{r}
library(tidyverse)
library(viridis)

make_grid_art <- function(xSize, ySize, grout, hFactor) {
  xWave <- seq.int(1:xSize)
  yWave <- seq.int(1:ySize)
  axMin <- min(min(xWave) - 1,min(yWave) - 1)
  axMax <- max(max(xWave) + 1,max(yWave) + 1)
  nSquares <- length(xWave) * length(yWave)
  df <- data.frame()
  x <- 0
  halfGrout <- (1 - grout) / 2
  id_fact = max(xSize,ySize)
  for (i in seq_along(yWave)) {
    yCentre <- yWave[i]
    for (j in seq_along(xWave)) {
      if(hFactor < 1) {
        hyst <- rnorm(8, halfGrout, 0)
      }
      else {
        hyst <- rnorm(8, halfGrout, sin(x / (nSquares - 1) * pi) / hFactor)
      }
      xCentre <- xWave[j]
      id <- ((i-1)*id_fact) + j
      edge_dist <- min(abs(i-1), abs(i-ySize),abs(j-1), abs(j-xSize))
      fill <- mean(hyst)
      lt <- c(xCentre - hyst[1],yCentre - hyst[2], id, fill, edge_dist)
      rt <- c(xCentre + hyst[3],yCentre - hyst[4], id, fill, edge_dist)
      rb <- c(xCentre + hyst[5],yCentre + hyst[6], id, fill, edge_dist)
      lb <- c(xCentre - hyst[7],yCentre + hyst[8], id, fill, edge_dist)
      df <- rbind(df, lt,rt,rb,lb)
      x <- x + 1
    }
  }
  names(df) <- c("x", "y", "id", "fill", "dist")  
  p <- ggplot(df, aes(x=x, y=y, color=dist, fill=fill, group=id)) +
    geom_polygon(alpha=0.75) +
    scale_color_viridis(begin=0.35) +
    scale_fill_viridis() +
    theme_void() +
    guides(color=FALSE, fill=FALSE)
  print(p)
}
```

Then to create each image..
```{r}
# square grid with minimal hysteresis
make_grid_art(10,10,0.2,50)
# square grid (more squares) more hysteresis
make_grid_art(20,20,0.02,10)
# rectangular grid same hysteresis
make_grid_art(25,15,0,10)
# same grid with no hysteresis
make_grid_art(25,15,0.08,0)
# square grid moderate hysteresis and no grout
make_grid_art(20,20,0,10)
```
